### ISSUE TITLE
Question on performance 

### ISSUE THREAD

**Issue by yjh576** [open-mmlab/OpenUnReID#4]
hi，thanks for your work. 
 I have obtained bad performance on MMT and SpCL by only using your code and default setting .
For instance,
MMT(duke-to-market):
************************* Start validating market1501 on epoch 49 *************************n
[1mVal: [ 0/18][0m	Time 0.997 (0.997)	Data 0.353 (0.353)
[1mVal: [10/18][0m	Time 0.407 (0.493)	Data 0.000 (0.032)

Mean AP: 4.2%
CMC Scores:
  top-1           6.1%
  top-5          15.2%
  top-10         21.7%
Validating time:  0:00:22.068357
SpCL (unsupervised on market1501):
************************* Start validating market1501 on epoch 49 *************************n
[1mVal: [ 0/18][0m	Time 0.475 (0.475)	Data 0.299 (0.299)
[1mVal: [10/18][0m	Time 0.100 (0.147)	Data 0.000 (0.027)

Mean AP: 15.8%
CMC Scores:
  top-1          24.0%
  top-5          44.2%
  top-10         56.2%
Validating time:  0:00:14.673135

I suspect that I have overlooked something important. Can you give me a advise?

**Comment by yxgeee** [comment]
That's weird. Could you please provide the config files you used?

**Comment by yjh576** [comment]
SpCL(market-to-duke):
==========
Args:Namespace(config='SpCL/config.yaml', launcher='none', resume_from=None, set_cfgs=['TRAIN.val_freq', '10'], tcp_port='5017', work_dir='config')
==========
cfg.LOCAL_RANK: 0
cfg.DATA_ROOT: /open-reid/datasets
cfg.LOGS_ROOT: /data//open-reid/logs

cfg.MODEL = edict()
cfg.MODEL.backbone: resnet50
cfg.MODEL.pooling: gem
cfg.MODEL.embed_feat: 0
cfg.MODEL.dropout: 0.0
cfg.MODEL.dsbn: True
cfg.MODEL.sync_bn: True
cfg.MODEL.samples_per_bn: 16
cfg.MODEL.mean_net: False
cfg.MODEL.alpha: 0.999
cfg.MODEL.imagenet_pretrained: True
cfg.MODEL.source_pretrained: None

cfg.DATA = edict()
cfg.DATA.height: 256
cfg.DATA.width: 128
cfg.DATA.norm_mean: [0.485, 0.456, 0.406]
cfg.DATA.norm_std: [0.229, 0.224, 0.225]

cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.is_autoaug: False
cfg.DATA.TRAIN.is_flip: True
cfg.DATA.TRAIN.flip_prob: 0.5
cfg.DATA.TRAIN.is_pad: True
cfg.DATA.TRAIN.pad_size: 10
cfg.DATA.TRAIN.is_blur: False
cfg.DATA.TRAIN.blur_prob: 0.5
cfg.DATA.TRAIN.is_erase: True
cfg.DATA.TRAIN.erase_prob: 0.5
cfg.DATA.TRAIN.is_mutual_transform: False
cfg.DATA.TRAIN.mutual_times: 2

cfg.TRAIN = edict()
cfg.TRAIN.seed: 1
cfg.TRAIN.deterministic: True

cfg.TRAIN.datasets = edict()
cfg.TRAIN.datasets.market1501: trainval
cfg.TRAIN.datasets.dukemtmcreid: trainval
cfg.TRAIN.unsup_dataset_indexes: [1]
cfg.TRAIN.epochs: 50
cfg.TRAIN.iters: 400

cfg.TRAIN.LOSS = edict()

cfg.TRAIN.LOSS.losses = edict()
cfg.TRAIN.LOSS.losses.hybrid_memory: 1.0
cfg.TRAIN.LOSS.temp: 0.05
cfg.TRAIN.LOSS.momentum: 0.2
cfg.TRAIN.val_dataset: dukemtmcreid
cfg.TRAIN.val_freq: 10

cfg.TRAIN.SAMPLER = edict()
cfg.TRAIN.SAMPLER.num_instances: 4
cfg.TRAIN.SAMPLER.is_shuffle: True

cfg.TRAIN.LOADER = edict()
cfg.TRAIN.LOADER.samples_per_gpu: 16
cfg.TRAIN.LOADER.workers_per_gpu: 2

cfg.TRAIN.PSEUDO_LABELS = edict()
cfg.TRAIN.PSEUDO_LABELS.freq: 1
cfg.TRAIN.PSEUDO_LABELS.use_outliers: True
cfg.TRAIN.PSEUDO_LABELS.norm_feat: True
cfg.TRAIN.PSEUDO_LABELS.norm_center: True
cfg.TRAIN.PSEUDO_LABELS.cluster: dbscan
cfg.TRAIN.PSEUDO_LABELS.eps: [0.58, 0.6, 0.62]
cfg.TRAIN.PSEUDO_LABELS.min_samples: 4
cfg.TRAIN.PSEUDO_LABELS.dist_metric: jaccard
cfg.TRAIN.PSEUDO_LABELS.k1: 30
cfg.TRAIN.PSEUDO_LABELS.k2: 6
cfg.TRAIN.PSEUDO_LABELS.search_type: 0
cfg.TRAIN.PSEUDO_LABELS.cluster_num: None

cfg.TRAIN.OPTIM = edict()
cfg.TRAIN.OPTIM.optim: adam
cfg.TRAIN.OPTIM.lr: 0.00035
cfg.TRAIN.OPTIM.weight_decay: 0.0005

cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.lr_scheduler: single_step
cfg.TRAIN.SCHEDULER.stepsize: 20
cfg.TRAIN.SCHEDULER.gamma: 0.1

cfg.TEST = edict()
cfg.TEST.datasets: ['dukemtmcreid']

cfg.TEST.LOADER = edict()
cfg.TEST.LOADER.samples_per_gpu: 32
cfg.TEST.LOADER.workers_per_gpu: 2
cfg.TEST.dist_metric: euclidean
cfg.TEST.norm_feat: True
cfg.TEST.dist_cuda: True
cfg.TEST.rerank: False
cfg.TEST.search_type: 0
cfg.TEST.k1: 20
cfg.TEST.k2: 6
cfg.TEST.lambda_value: 0.3
cfg.launcher: none
cfg.tcp_port: 5017
cfg.work_dir: /open-reid/logs/config
cfg.total_gpus: 4
The training is in a un/semi-supervised manner with 2 dataset(s) (['market1501', 'dukemtmcreid']),
where ['dukemtmcreid'] have no labels.
[1m=> Loaded trainval from Market1501[0m
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
    751 |    12936 |         6
  ----------------------------
[1m=> Loaded trainval from DukeMTMCreID[0m
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
      1 |    16522 |         8
  ----------------------------


[1mEpoch: [49][390/400][0m	Time 0.304 (0.353)	hybrid_memory 4.683 (4.941)

************************* Start validating dukemtmcreid on epoch 49 *************************n
[1mVal: [ 0/23][0m	Time 0.506 (0.506)	Data 0.317 (0.317)
[1mVal: [10/23][0m	Time 0.140 (0.181)	Data 0.000 (0.029)
[1mVal: [20/23][0m	Time 0.104 (0.149)	Data 0.000 (0.015)


Mean AP: 11.2%
CMC Scores:
  top-1          16.3%
  top-5          25.9%
  top-10         33.0%
Validating time:  0:00:15.829343

************************* Finished validating *************************

[92m
 * Finished epoch  49  mAP: 11.2%  best: 11.6%
[0m
=> Loaded checkpoint '/open-reid/logs/config/model_best.pth'
[1m=> Loaded query from DukeMTMCreID[0m
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
    702 |     2228 |         8
  ----------------------------
[1m=> Loaded gallery from DukeMTMCreID[0m
  ----------------------------
  # ids | # images | # cameras
  ----------------------------
   1110 |    17661 |         8
  ----------------------------

******************************* Start testing dukemtmcreid *******************************

[1mTest: [  0/156][0m	Time 0.646 (0.646)	Data 0.346 (0.346)
[1mTest: [ 10/156][0m	Time 0.155 (0.199)	Data 0.000 (0.032)
[1mTest: [ 20/156][0m	Time 0.135 (0.175)	Data 0.000 (0.017)
[1mTest: [ 30/156][0m	Time 0.160 (0.167)	Data 0.000 (0.012)
[1mTest: [ 40/156][0m	Time 0.141 (0.164)	Data 0.000 (0.009)
[1mTest: [ 50/156][0m	Time 0.134 (0.161)	Data 0.000 (0.007)
[1mTest: [ 60/156][0m	Time 0.144 (0.158)	Data 0.000 (0.006)
[1mTest: [ 70/156][0m	Time 0.145 (0.155)	Data 0.000 (0.005)
[1mTest: [ 80/156][0m	Time 0.134 (0.153)	Data 0.000 (0.005)
[1mTest: [ 90/156][0m	Time 0.157 (0.153)	Data 0.000 (0.004)
[1mTest: [100/156][0m	Time 0.127 (0.152)	Data 0.000 (0.004)
[1mTest: [110/156][0m	Time 0.146 (0.151)	Data 0.000 (0.003)
[1mTest: [120/156][0m	Time 0.136 (0.150)	Data 0.000 (0.003)
[1mTest: [130/156][0m	Time 0.136 (0.150)	Data 0.000 (0.003)
[1mTest: [140/156][0m	Time 0.146 (0.149)	Data 0.000 (0.003)
[1mTest: [150/156][0m	Time 0.138 (0.148)	Data 0.000 (0.003)


Mean AP: 5.3%
CMC Scores:
  top-1           9.7%
  top-5          19.3%
  top-10         24.1%
Testing time:  0:00:38.719870

******************************* Finished testing *******************************

**Comment by yxgeee** [comment]
Hi,
The config looks normal, could you please provide the number of clusters before each epoch? You can achieve it by `cat log.txt | grep Statistics`.

By the way, I re-trained SpCL (unsupervised market1501) upon receiving your issue. I have just trained for 8 epochs, however, the first validation result looks normal:
```
 * Finished epoch   4  mAP: 34.5%  best: 34.5% *
```
It seems that your problem does not occur in my experiments. We need to figure your problem step by step, so first, please provide the number of clusters in your experiments.

**Comment by yxgeee** [comment]
You could also provide your validation results during training by `cat log.txt | grep mAP`

**Comment by yjh576** [comment]
==> Statistics for dukemtmcreid on epoch 0: 429 clusters, 9747 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 1: 254 clusters, 10355 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 2: 201 clusters, 10515 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 3: 267 clusters, 10335 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 4: 300 clusters, 10050 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 5: 345 clusters, 9691 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 6: 373 clusters, 9547 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 7: 377 clusters, 9509 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 8: 401 clusters, 9552 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 9: 411 clusters, 9258 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 10: 379 clusters, 9408 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 11: 408 clusters, 9263 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 12: 397 clusters, 9340 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 13: 381 clusters, 9256 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 14: 395 clusters, 9300 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 15: 399 clusters, 9270 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 16: 387 clusters, 9417 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 17: 399 clusters, 9407 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 18: 375 clusters, 9605 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 19: 404 clusters, 9461 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 20: 379 clusters, 9608 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 21: 389 clusters, 9447 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 22: 390 clusters, 9400 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 23: 382 clusters, 9283 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 24: 416 clusters, 9287 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 25: 380 clusters, 9281 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 26: 379 clusters, 9266 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 27: 374 clusters, 9211 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 28: 375 clusters, 9326 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 29: 384 clusters, 9153 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 30: 374 clusters, 8984 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 31: 364 clusters, 9068 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 32: 368 clusters, 8995 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 33: 384 clusters, 8882 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 34: 373 clusters, 9063 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 35: 370 clusters, 8893 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 36: 387 clusters, 8783 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 37: 373 clusters, 8950 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 38: 362 clusters, 8891 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 39: 379 clusters, 8958 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 40: 357 clusters, 9065 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 41: 370 clusters, 8963 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 42: 381 clusters, 8998 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 43: 378 clusters, 9001 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 44: 378 clusters, 8926 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 45: 361 clusters, 8986 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 46: 348 clusters, 9006 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 47: 395 clusters, 9114 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 48: 383 clusters, 8940 un-clustered instances, 0 unused instances
==> Statistics for dukemtmcreid on epoch 49: 390 clusters, 8802 un-clustered instances, 0 unused instances

**Comment by yxgeee** [comment]
The number of clusters is abnormal. It seems the label noise has been amplificated. Is it the market->duke UDA experiment with SpCL? Let me try it.

**Comment by yjh576** [comment]
Yes.  However, the number of clusters is abnormal, thus I also want to sure it again.  The config files I used is: 

MODEL:
  # architecture
  backbone: 'resnet50'
  pooling: 'gem'
  embed_feat: 0
  dropout: 0.

  dsbn: True

  sync_bn: True
  samples_per_bn: 16

  mean_net: False
  alpha: 0.999

  # pretraining
  imagenet_pretrained: True
  source_pretrained: null


DATA:

  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

  TRAIN:
    # augmentation
    is_autoaug: False

    is_flip: True
    flip_prob: 0.5

    is_pad: True
    pad_size: 10

    is_blur: False
    blur_prob: 0.5

    is_erase: True
    erase_prob: 0.5

    # dual augmentation for MMT
    is_mutual_transform: False
    mutual_times: 2


TRAIN:
  seed: 1
  deterministic: True

  # datasets
  datasets: {'market1501': 'trainval', 'dukemtmcreid': 'trainval'}
  unsup_dataset_indexes: [1,]

  epochs: 50
  iters: 400

  LOSS:
    losses: {'hybrid_memory': 1.,}
    temp: 0.05
    momentum: 0.2

  # validate
  val_dataset: 'dukemtmcreid'
  val_freq: 5

  # sampler
  SAMPLER:
    num_instances: 4
    is_shuffle: True

  # data loader
  LOADER:
    samples_per_gpu: 16
    workers_per_gpu: 2

  # pseudo labels
  PSEUDO_LABELS:
    freq: 1 # epochs
    use_outliers: True
    norm_feat: True
    norm_center: True

    cluster: 'dbscan'
    eps: [0.58, 0.6, 0.62]
    min_samples: 4 # for dbscan
    dist_metric: 'jaccard'
    k1: 30 # for jaccard distance
    k2: 6 # for jaccard distance
    search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
    cluster_num: null

    # cluster: 'kmeans'
    # cluster_num: [500,]
    # dist_cuda: True

  # optim
  OPTIM:
    optim: 'adam'
    lr: 0.00035
    weight_decay: 0.0005

  SCHEDULER:
    lr_scheduler: 'single_step'
    stepsize: 20
    gamma: 0.1


TEST:

  # datasets
  datasets: ['dukemtmcreid',]

  # data loader
  LOADER:
    samples_per_gpu: 32
    workers_per_gpu: 2

  # ranking setting
  dist_metric: 'euclidean'
  norm_feat: True
  dist_cuda: True

  # post processing
  rerank: False
  search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
  k1: 20
  k2: 6
  lambda_value: 0.3


Thank you for your help. I have a new understanding.

**Comment by yxgeee** [comment]
I cannot find any problem in your config file, and here is mine, you could double check:
```
DATA_ROOT: '../datasets/'
LOGS_ROOT: '../logs/'


MODEL:
  # architecture
  backbone: 'resnet50'
  pooling: 'gem'
  embed_feat: 0
  dropout: 0.

  dsbn: True

  sync_bn: True
  samples_per_bn: 16

  mean_net: False
  alpha: 0.999

  # pretraining
  imagenet_pretrained: True
  source_pretrained: null


DATA:

  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

  TRAIN:
    # augmentation
    is_autoaug: False

    is_flip: True
    flip_prob: 0.5

    is_pad: True
    pad_size: 10

    is_blur: False
    blur_prob: 0.5

    is_erase: True
    erase_prob: 0.5

    # dual augmentation for MMT
    is_mutual_transform: False
    mutual_times: 2


TRAIN:
  seed: 1
  deterministic: True
  # mixed precision training for PyTorch>=1.6
  amp: False

  # datasets
  # datasets: {'market1501': 'trainval',}
  datasets: {'market1501': 'trainval', 'dukemtmcreid': 'trainval'}
  unsup_dataset_indexes: [1,]

  epochs: 50
  iters: 400

  LOSS:
    losses: {'hybrid_memory': 1.,}
    temp: 0.05
    momentum: 0.2

  # validate
  val_dataset: 'dukemtmcreid'
  val_freq: 5

  # sampler
  SAMPLER:
    num_instances: 4
    is_shuffle: True

  # data loader
  LOADER:
    samples_per_gpu: 16
    workers_per_gpu: 2

  # pseudo labels
  PSEUDO_LABELS:
    freq: 1 # epochs
    use_outliers: True
    norm_feat: True
    norm_center: True

    cluster: 'dbscan'
    eps: [0.58, 0.6, 0.62]
    min_samples: 4 # for dbscan
    dist_metric: 'jaccard'
    k1: 30 # for jaccard distance
    k2: 6 # for jaccard distance
    search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
    cluster_num: null

    # cluster: 'kmeans'
    # cluster_num: [500,]
    # dist_cuda: True

  # optim
  OPTIM:
    optim: 'adam'
    lr: 0.00035
    weight_decay: 0.0005

  SCHEDULER:
    lr_scheduler: 'single_step'
    stepsize: 20
    gamma: 0.1


TEST:

  # datasets
  datasets: ['dukemtmcreid',]

  # data loader
  LOADER:
    samples_per_gpu: 32
    workers_per_gpu: 2

  # ranking setting
  dist_metric: 'euclidean'
  norm_feat: True
  dist_cuda: True

  # post processing
  rerank: False
  search_type: 0 # 0,1,2 for GPU, 3 for CPU (work for faiss)
  k1: 20
  k2: 6
  lambda_value: 0.3
```
