### ISSUE TITLE
severe overfitting with a single GPU

### ISSUE THREAD

**Issue by hartvon** [open-mmlab/OpenUnReID#53]
您好，
我在使用`strong_baseline`方法进行DukeMTMC-reID -> Market-1501的UDA训练时出现了严重的过拟合。

这是我对config的修改（我的设备最多支持batch size为8）：
- samples_per_gpu: 16 -> 8
- lr: 0.00035 -> 0.000035

这是我的训练log：
```yaml
# performance on val dataset
Mean AP: 81.4%
CMC Scores:
  top-1          91.4%
  top-5          97.5%
  top-10         98.8%
Validating time:  0:00:09.783462
* Finished epoch  49  mAP: 81.4%  best: 81.4% *

# performance on test dataset
Mean AP: 55.4%
CMC Scores:
  top-1          78.6%
  top-5          91.6%
  top-10         94.5%
```

验证精度和测试精度相差很大，并且最终的测试精度与leaderboard上的差了近20%

请问我需要怎么调整以解决这一问题，非常感谢！
